<?php

namespace ContainerYFUdMkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_RememberMeHandler_MainService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'security.authenticator.remember_me_handler.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\RememberMe\SignatureRememberMeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['PrestaShopBundle\\Security\\Admin\\EmployeeProvider'] ?? self::getEmployeeProviderService($container));

        if (isset($container->privates['security.authenticator.remember_me_handler.main'])) {
            return $container->privates['security.authenticator.remember_me_handler.main'];
        }

        $instance = new \Symfony\Component\Security\Http\RememberMe\SignatureRememberMeHandler(new \Symfony\Component\Security\Core\Signature\SignatureHasher(($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), ['password'], 'WF8EUROnQOgFaw7kqOf78qcjuFGa6xbRLWZ2xGS1NwibSORRw5IC6sCK3LxZO4PQ', NULL, NULL), $a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ['secret' => 'WF8EUROnQOgFaw7kqOf78qcjuFGa6xbRLWZ2xGS1NwibSORRw5IC6sCK3LxZO4PQ', 'lifetime' => 1728000, 'remember_me_parameter' => 'stay_logged_in', 'signature_properties' => ['password'], 'user_providers' => [], 'catch_exceptions' => true, 'name' => 'REMEMBERME', 'path' => '/', 'domain' => NULL, 'secure' => NULL, 'httponly' => true, 'samesite' => NULL, 'always_remember_me' => false], ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)));

        if (isset($container->privates['security.authenticator.remember_me_handler.main'])) {
            return $container->privates['security.authenticator.remember_me_handler.main'];
        }

        return $container->privates['security.authenticator.remember_me_handler.main'] = $instance;
    }
}
