<?php

namespace ContainerBRxyiyI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckTranslationFixturesService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Command\CheckTranslationFixtures' shared service.
     *
     * @return \PrestaShopBundle\Command\CheckTranslationFixtures
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShopBundle\\Command\\CheckTranslationFixtures'] = new \PrestaShopBundle\Command\CheckTranslationFixtures();
    }
}
