<?php

namespace ContainerBRxyiyI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactFiltersService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zCb2Uqm.PrestaShop\PrestaShop\Core\Search\Filters\ContactFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\ContactFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zCb2Uqm": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ContactFilters" but no such service exists.');
    }
}
