<?php

namespace ContainerBRxyiyI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestaShopAdminControllerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Controller\Admin\PrestaShopAdminController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\PrestaShopAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\PrestaShopAdminController'] = $instance = new \PrestaShopBundle\Controller\Admin\PrestaShopAdminController();

        $instance->setContainer(($container->privates['.service_locator.GcEKB96'] ?? $container->load('get_ServiceLocator_GcEKB96Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\PrestaShopAdminController', $container));

        return $instance;
    }
}
