<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYFUdMkr\AdminKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYFUdMkr/AdminKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYFUdMkr.legacy');

    return;
}

if (!\class_exists(AdminKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYFUdMkr\AdminKernelDevDebugContainer::class, AdminKernelDevDebugContainer::class, false);
}

return new \ContainerYFUdMkr\AdminKernelDevDebugContainer([
    'container.build_hash' => 'YFUdMkr',
    'container.build_id' => '75b39515',
    'container.build_time' => 1781020571,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYFUdMkr');
