<?php

namespace ContainerPuxHBIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\DiscountController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Sell\Catalog\DiscountController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\DiscountController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\DiscountController();

        $instance->setContainer(($container->privates['.service_locator.GcEKB96'] ?? $container->load('get_ServiceLocator_GcEKB96Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\DiscountController', $container));

        return $instance;
    }
}
