<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container595euK4\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container595euK4/AdminKernelProdContainer.php') {
    touch(__DIR__.'/Container595euK4.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\Container595euK4\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \Container595euK4\AdminKernelProdContainer([
    'container.build_hash' => '595euK4',
    'container.build_id' => '30652162',
    'container.build_time' => 1780479593,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container595euK4');
