<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEQJRM0f\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEQJRM0f/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEQJRM0f.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerEQJRM0f\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerEQJRM0f\AdminKernelProdContainer([
    'container.build_hash' => 'EQJRM0f',
    'container.build_id' => 'dfb38276',
    'container.build_time' => 1781020474,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEQJRM0f');
